name: Pull Docker Images and Package
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: Input the image name, can be multiple image names separated by ','
        required: true
        default: 'alpine:latest,ubuntu:latest'
      arch:
        description: arch
        required: true
        default: amd64
        type: choice
        options:
          - amd64
          - arm64
          - arm32

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
          docker system prune -a -f
          docker volume prune -f

    - name: Pull Docker Images and Package
      run: |
        platform=${{ github.event.inputs.arch }}
        if [[ $platform == 'arm32' ]]; then platform="arm/v7"; fi
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          # trim the prefix or suffix spaces, can also use image=$(echo $image | xargs)
          # see also https://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
          image=$(echo $image)
          docker pull "${image}" --platform "linux/${{ github.event.inputs.arch }}"
          docker save "${image}" -o "${image//\//_}-${{ github.event.inputs.arch }}.tar"
        done

    - name: Compress the saved docker images
      run: |
        tar -cJf ${{ github.event.inputs.arch }}-images.tar.xz *-${{ github.event.inputs.arch }}.tar
        ls -l *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.arch }}-docker-images
        path: ${{ github.event.inputs.arch }}-images.tar.xz
        retention-days: 30
